version: '3'
services:
  server:
    image: factoriotools/factorio:stable
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - data:/factorio
    restart: always
volumes:
  data:
